services:
  - type: web
    name: kebapzade-qr-menu
    env: docker
    plan: free
    region: frankfurt
    healthCheckPath: /health.php
    envVars:
      - key: APP_NAME
        value: "Kebapzade Premium"
      - key: ADMIN_EMAIL
        value: "admin@kebapzade.com"
      - key: ADMIN_PASSWORD
        value: "Admin123456*"
