<?php
declare(strict_types=1);

return [
  'categories' => [
    ['corba-salatalar', 'Çorba & Salatalar', 'Soup & Salads', 10],
    ['mezeler', 'Mezeler', 'Cold Appetizers / Mezze', 20],
    ['ara-sicaklar', 'Ara Sıcaklar', 'Hot Appetizers', 30],
    ['tavuk-yemekleri', 'Tavuk Yemekleri', 'Chicken Foods', 40],
    ['yoresel-yemekler', 'Yöresel Yemekler', 'Local Foods', 50],
    ['izgaralar', 'Izgaralar', 'Grilled Kebabs', 60],
    ['kebaplar', 'Kebaplar', 'Special Kebabs', 70],
    ['karisik-izgaralar', 'Karışık Izgaralar', 'Mixed Grills', 80],
    ['ozel-yemekler', 'Özel Yemekler', 'Special Foods', 90],
    ['tatlilar', 'Tatlılar', 'Desserts', 100],
    ['yoresel-icecekler', 'Yöresel İçecekler', 'Traditional Drinks', 110],
    ['mesrubatlar', 'Meşrubatlar', 'Soft Drinks', 120],
    ['sicak-icecekler', 'Sıcak İçecekler', 'Hot Drinks', 130],
  ],
  'items' => [
    ['corba-salatalar', 'Mercimek Çorbası', 'Red Lentil Soup', 'Kırmızı mercimek, tereyağı, taze sebze ve baharatlarla.', 'Red lentils, butter, vegetables and spices.', 0, 0, 1],
    ['corba-salatalar', 'Çoban Salatası', 'Shepherd’s Salad', 'Domates, salatalık, biber, maydanoz, kuru soğan, zeytinyağı ve nar ekşili sos.', 'Tomato, cucumber, pepper, parsley, onion, olive oil and pomegranate sauce.', 0, 0, 1],
    ['corba-salatalar', 'Nurdağ Salatası', 'Walnut Salad', 'Ceviz, domates, salatalık, biber, maydanoz, kuru soğan, zeytinyağı ve nar ekşili sos.', 'Walnut, tomato, cucumber, pepper, parsley, onion, olive oil and pomegranate sauce.', 0, 0, 1],
    ['corba-salatalar', 'Mevsim Salata', 'Seasonal Salad', 'Mevsim yeşillikleri, domates, salatalık, zeytinyağı ve nar ekşili sos.', 'Seasonal greens, tomato, cucumber, olive oil and pomegranate sauce.', 0, 0, 1],
    ['mezeler', 'Közlenmiş Patlıcan Salatası', 'Grilled Aubergine Salad', 'Köz patlıcan, köz domates, köz biber, sarımsak ve zeytinyağı.', 'Roasted aubergine, tomato, pepper, garlic and olive oil.', 0, 0, 1],
    ['mezeler', 'Hatay Humus', 'Hummus', 'Nohut ezmesi, kimyon, sarımsak, limon, tahin ve zeytinyağı.', 'Chickpea purée, cumin, garlic, lemon, tahini and olive oil.', 1, 0, 1],
    ['mezeler', 'Antep Ezme', 'Spicy Tomato Mezze', 'Taze sebzeler, biber salçası, baharat, zeytinyağı ve nar ekşili sos.', 'Fresh vegetables, pepper paste, spices, olive oil and pomegranate sauce.', 0, 1, 1],
    ['mezeler', 'Zeytinyağlı Enginar', 'Artichoke with Olive Oil', 'Zeytinyağlı enginar ve sebzeler.', 'Artichoke and vegetables with olive oil.', 0, 0, 1],
    ['mezeler', 'Haydari', 'Haydari', 'Süzme yoğurt, kuru nane, dereotu, sarımsak, baharat ve zeytinyağı.', 'Thick yoghurt, mint, dill, garlic, spices and olive oil.', 0, 0, 1],
    ['mezeler', 'Yöresel Yoğurt', 'Plain Yoghurt', 'Doğal sütten yöresel yoğurt.', 'Regional plain yoghurt made from natural milk.', 0, 0, 1],
    ['mezeler', 'Közde Sarımsak', 'Roasted Garlic', 'Taş fırında közlenmiş sarımsak, nar ekşili baharatlı özel sos ile.', 'Stone-oven roasted garlic with pomegranate sauce.', 0, 0, 1],
    ['mezeler', 'Karışık Meze Tabağı', 'Mixed Mezze Platter', 'Patlıcan, humus, ezme ve haydari.', 'Roasted aubergine, hummus, spicy mezze and haydari.', 1, 0, 1],
    ['ara-sicaklar', 'Kaşarlı Mantar Kiremit', 'Mushroom with Cheese', 'Taze mantar, tereyağı ve kaşar peyniri taş fırında.', 'Fresh mushroom, butter and cheese cooked in a stone oven.', 0, 0, 1],
    ['ara-sicaklar', 'Humus Tereyağlı Cevizli', 'Baked Walnut Hummus', 'Hatay usulü humus, ceviz ve tereyağı ile taş fırında.', 'Hummus with walnut and butter, baked in a stone oven.', 1, 0, 1],
    ['ara-sicaklar', 'Falafel', 'Falafel', 'Nohut, taze sebzeler ve baharatlarla.', 'Chickpea, fresh herbs and spices.', 0, 0, 1],
    ['ara-sicaklar', 'İçli Köfte (1 Adet)', 'Stuffed Meatball (1 Piece)', 'Kıyma, ceviz, üzüm, bulgur ve baharatlarla.', 'Bulgur shell stuffed with minced beef, walnut and spices.', 0, 0, 0],
    ['ara-sicaklar', 'Patates Kızartması', 'French Fries', 'Patates kızartması.', 'French fries.', 0, 0, 1],
    ['tavuk-yemekleri', 'Tavuk Köri', 'Chicken Curry', 'Köri sosu, taze süt, mantar, tavuk ve sebzeler; taş fırında.', 'Chicken, curry sauce, milk, mushroom and vegetables; stone-oven cooked.', 1, 0, 0],
    ['tavuk-yemekleri', 'Tavuk Güveç', 'Chicken Casserole', 'Tavuk, közlenmiş patlıcan ve sebzeler taş fırında.', 'Chicken, smoked aubergine and vegetables cooked in a stone oven.', 0, 0, 0],
    ['tavuk-yemekleri', 'Kiremitte Kaşarlı Tavuk', 'Baked Chicken with Cheese', 'Tavuk, mantar, domates, sarımsak ve kaşar peyniri taş fırında.', 'Chicken, mushroom, tomato, garlic and cheese cooked in a stone oven.', 0, 0, 0],
    ['tavuk-yemekleri', 'Tereyağlı Pirinç Pilavı', 'White Rice with Butter', 'Tereyağlı pirinç pilavı.', 'White rice with butter.', 0, 0, 1],
    ['yoresel-yemekler', 'Testi Kebabı', 'Pottery Kebab – Beef', 'Dana eti, domates, biber, soğan, sarımsak ve baharatlar; tereyağlı pirinç pilavı ile.', 'Beef, tomato, pepper, onion, garlic and spices; served with rice.', 1, 0, 0],
    ['yoresel-yemekler', 'Tavuk Testi', 'Pottery Kebab – Chicken', 'Tavuk, domates, biber, soğan, sarımsak ve baharatlar; pirinç pilavı ile.', 'Chicken, tomato, pepper, onion, garlic and spices; served with rice.', 0, 0, 0],
    ['yoresel-yemekler', 'Kurufasulye', 'White Beans Stew', 'Geleneksel kuru fasulye; pirinç pilavı ile.', 'Traditional white beans stew served with rice.', 0, 0, 0],
    ['yoresel-yemekler', 'Sebzeli Testi', 'Vegetarian Pottery Kebab', 'Sebzeler testi içinde taş fırında pişirilir.', 'Vegetables cooked in pottery in a stone oven.', 0, 0, 1],
    ['yoresel-yemekler', 'Kiremitte Köfte Izgara', 'Meatball Casserole', 'Izgara köfte ve özel domates sosu.', 'Grilled meatballs with special tomato sauce.', 0, 0, 0],
    ['yoresel-yemekler', 'Kebapzade Güveç', 'Kebapzade Beef Casserole', 'Köz patlıcan, tereyağı, domates, sarımsak ve dana eti taş fırında.', 'Beef, roasted aubergine, butter, tomato and garlic, stone-oven cooked.', 1, 0, 0],
    ['yoresel-yemekler', 'Dana Kavurma', 'Beef Kavurma', 'Yavaş pişmiş dana kavurma, tereyağlı pirinç pilavı ile.', 'Slow-cooked beef kavurma served with buttered rice.', 0, 0, 0],
    ['izgaralar', 'Köfte Izgara', 'Grilled Meatball', 'Sumaklı soğan piyazı, domates, yeşil biber ızgara ve lavaş.', 'Grilled meatball with sumac onion, tomato, green pepper and lavash.', 0, 0, 0],
    ['izgaralar', 'Tavuk Şiş', 'Chicken Shish Kebab', 'Sumaklı soğan piyazı, domates, yeşil biber ızgara ve lavaş.', 'Chicken shish with sumac onion, tomato, green pepper and lavash.', 0, 0, 0],
    ['izgaralar', 'Tavuk Kanat', 'Chicken Wings', 'Sumaklı soğan piyazı, domates, yeşil biber ızgara ve lavaş.', 'Chicken wings with sumac onion, tomato, green pepper and lavash.', 0, 0, 0],
    ['kebaplar', 'Adana Kebap', 'Adana Kebab', 'Kömür ateşinde; sumaklı soğan, domates, biber ve lavaş ile.', 'Charcoal-grilled Adana kebab with sumac onion, tomato, pepper and lavash.', 1, 1, 0],
    ['kebaplar', 'Antep Fıstıklı Kebap', 'Pistachio Kebab', 'Kıyma ve Antep fıstığı; sumaklı soğan, domates, biber ve lavaş ile.', 'Minced meat and pistachio kebab with sumac onion, tomato, pepper and lavash.', 1, 0, 0],
    ['kebaplar', 'Kuzu Pirzola', 'Lamb Chops', 'Sumaklı soğan piyazı, domates, yeşil biber ızgara ve lavaş.', 'Lamb chops with sumac onion, tomato, green pepper and lavash.', 0, 0, 0],
    ['karisik-izgaralar', 'Karışık Izgara', 'Mixed Grill', 'Dana şiş, Adana kebap, tavuk kanat ve tavuk şiş.', 'Beef skewers, Adana kebab, chicken wings and chicken skewers.', 1, 0, 0],
    ['karisik-izgaralar', 'Karışık Kebapzade Izgara', 'Mixed Kebapzade Grill', 'Kuzu pirzola, dana şiş, Adana kebap, fıstıklı kebap ve içli köfte.', 'Lamb chops, beef shish, Adana kebab, pistachio kebab and stuffed meatball.', 1, 0, 0],
    ['ozel-yemekler', 'Kuzu Pirzola Taş Fırında', 'Lamb Chops on Pottery', 'Taş fırında pişirilen kuzu pirzola; karışık meze ile.', 'Stone-oven lamb chops served with mixed mezze.', 1, 0, 0],
    ['ozel-yemekler', 'Tuzda Tavuk Fırında', 'Salt-Crust Chicken', 'İç pilavla doldurulan tavuk kaya tuzuyla kaplanıp taş fırında pişirilir. Ön sipariş gerektirir.', 'Chicken stuffed with rice, covered in salt and roasted. Advance order required.', 1, 0, 0],
    ['ozel-yemekler', 'Taş Fırında Tavuk Pirzola', 'Chicken Chops on Pottery', 'Taş fırında pişirilir ve karışık meze ile.', 'Stone-oven chicken chops served with mixed mezze.', 0, 0, 0],
    ['ozel-yemekler', 'Taş Fırında Somon', 'Oven-Baked Salmon', 'Taş fırında pişirilir ve karışık meze ile.', 'Stone-oven salmon served with mixed mezze.', 0, 0, 0],
    ['tatlilar', 'Hatay Kabak Tatlısı', 'Crispy Pumpkin Dessert', 'Kireçte kıtır kabak tatlısı, ceviz ve tahin ile.', 'Crispy pumpkin dessert with walnut and tahini.', 1, 0, 1],
    ['tatlilar', 'Afyon Kabak Tatlısı', 'Creamy Pumpkin Dessert', 'Kabak tatlısı, tahin ve ceviz ile.', 'Pumpkin dessert with tahini and walnut.', 0, 0, 1],
    ['tatlilar', 'Dondurmalı Afyon Kabak Tatlısı', 'Creamy Pumpkin Dessert & Ice Cream', 'Afyon kabak tatlısı, dondurma, tahin ve ceviz ile.', 'Pumpkin dessert with ice cream, tahini and walnut.', 0, 0, 1],
    ['tatlilar', 'Havuç Dilimi Baklava', 'Pistachio Baklava', 'Tereyağlı, Antep fıstıklı havuç dilimi baklava.', 'Butter and pistachio baklava.', 1, 0, 1],
    ['tatlilar', 'Dondurmalı Havuç Dilimi Baklava', 'Pistachio Baklava with Ice Cream', 'Havuç dilimi baklava ve dondurma.', 'Pistachio baklava with ice cream.', 0, 0, 1],
    ['tatlilar', 'Fıstıklı Maraş Dondurması', 'Pistachio Ice Cream', 'Maraş usulü fıstıklı dondurma.', 'Maraş-style pistachio ice cream.', 0, 0, 1],
    ['yoresel-icecekler', 'Şıra (Kuru Üzüm Suyu)', 'Grape Juice', 'Geleneksel kuru üzüm içeceği.', 'Traditional grape drink.', 1, 0, 1],
    ['yoresel-icecekler', 'Yöresel Ayran', 'Ayran Drink', 'Yöresel ayran.', 'Traditional yoghurt drink.', 0, 0, 1],
    ['yoresel-icecekler', 'Multimix Meyve Suyu %100', 'Multimix Fruit Juice 100%', '%100 meyve suyu.', '100% fruit juice.', 0, 0, 1],
    ['yoresel-icecekler', 'Antioksidan Meyve Suyu %100', 'Antioxidant Juice 100%', '%100 meyve suyu.', '100% fruit juice.', 0, 0, 1],
    ['mesrubatlar', 'Küçük Su (0,33 L)', 'Water Small (0.33 L)', 'Şişe su.', 'Bottled water.', 0, 0, 1],
    ['mesrubatlar', 'Büyük Su (0,75 L)', 'Water Large (0.75 L)', 'Şişe su.', 'Bottled water.', 0, 0, 1],
    ['mesrubatlar', 'Maden Suyu (20 cl)', 'Sparkling Water (20 cl)', 'Maden suyu.', 'Sparkling water.', 0, 0, 1],
    ['mesrubatlar', 'Kola / Portakal / Gazoz / Ice Tea', 'Cola / Orange / Soda / Ice Tea', 'Soğuk meşrubat seçenekleri.', 'Assorted soft drinks.', 0, 0, 1],
    ['mesrubatlar', 'Meyve Suyu', 'Fruit Juice', 'Meyve suyu.', 'Fruit juice.', 0, 0, 1],
    ['mesrubatlar', 'Şalgam Suyu', 'Turnip Juice', 'Şalgam suyu.', 'Turnip juice.', 0, 1, 1],
    ['mesrubatlar', 'Kapalı Ayran', 'Ayran in a Cup', 'Kapalı ayran.', 'Packaged ayran.', 0, 0, 1],
    ['sicak-icecekler', 'Çay', 'Tea', 'Siyah çay; elma, limon, portakal çayı veya sıcak su seçenekleri.', 'Black tea; apple, lemon, orange tea or hot water options.', 0, 0, 1],
    ['sicak-icecekler', 'Yeşil Çay', 'Green Tea', 'Yeşil çay.', 'Green tea.', 0, 0, 1],
    ['sicak-icecekler', 'Türk Kahvesi', 'Turkish Coffee', 'Geleneksel Türk kahvesi.', 'Traditional Turkish coffee.', 1, 0, 1],
    ['sicak-icecekler', 'Neskafe Klasik', 'Nescafe Classic', 'Klasik hazır kahve.', 'Classic instant coffee.', 0, 0, 1],
  ],
];
